%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\local\Mipt\Lab\2nd_year\3_3_4\data.xls
%    Worksheet: ??????????
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/09/21 18:53:49

%% Import the data
[~, ~, raw] = xlsread('C:\local\Mipt\Lab\2nd_year\3_3_4\data.xls','?????????? ');
raw = raw(6:16,[3,end]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Exclude rows with non-numeric cells
R = ~all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2); 
raw(R,:) = [];
%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
I = data(:,1);
Phi = data(:,2);

%% Clear temporary variables
clearvars data raw R;

f = fit(I,Phi,'Poly2');
plot(f,I,Phi);
make_fancy('Current', 'Stream', 'Calibration');
%make_simple_graph(I,Phi, 'Current', 'Stream', 'Calibration'); 


