function make_simple_graph(X1, Y1, x_name, y_name, my_title)
%CREATEFIGURE(X1, Y1) lol
%  X1:  scatter x
%  Y1:  scatter y

%  Auto-generated by MATLAB on 21-Sep-2018 19:02:18

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1);

% Create xlabel
xlabel(x_name);

% Create title
title(my_title);

% Create ylabel
ylabel(y_name);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
